# This workflow will do a clean install of node dependencies, build the source code and run tests

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '20'

    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm i
    - run: npm run lint
    - run: npm run build
    - run: npm run test
    - run: npm run docs

    - name: Codecov
      uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
      with:
        directory: ./build/coverage
        flags: unittests
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  