# This workflow will do a clean install of node dependencies, build the source code, publish to npm, and deploy latest docs to GitHub pages

name: Release

on:
  release:
    types: [ published ]
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '20'

    steps:
    - name: Checkout
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm i
    - run: npm run build
    - run: npm run docs

    - name: Publish
      if: success()
      run: ./deploy.sh
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@c05ee637ec73429400a359430db8e5629f3f2564 # v4.0.0
      with:
        commit_message: Deploy morganstanley/desktopJS
        build_dir: docs/
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}